### ISSUE TITLE
some errors when invalid secret was supplied

### ISSUE THREAD

**Issue by jmikerq** [dexterlabora/node-red-contrib-meraki-cmx#1]
In the case which the meraki node was supplied with an invalid secret, the node status shows as "invalid post", and shows this in the node-red log:

```
/public/scanning Received Data, validating secret
processing Meraki observation data
Error: Invalid Secret from: 172.17.0.1
Error. Invalid POST from 172.17.0.1

ReferenceError: msg is not defined
at /user/node_modules/node-red-contrib-meraki-cmx/cmx/merakiCMX.js:164:76
at Layer.handle [as handle_request] (/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
at next (/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
at /node_modules/node-red/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
at next (/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
at urlencodedParser (/shared_nodes/node-red-contrib-freeboard/node_modules/body-parser/lib/types/urlencoded.js:77:44)
at Layer.handle [as handle_request] (/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
at /node_modules/node-red/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
at next (/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
at expressInit (/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
at Layer.handle [as handle_request] (/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
at /node_modules/node-red/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
at next (/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
at query (/node_modules/node-red/node_modules/express/lib/middleware/query.js:44:5)
at Layer.handle [as handle_request] (/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)

Error: Can't set headers after they are sent.
at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
at ServerResponse.header (/node_modules/node-red/node_modules/express/lib/response.js:730:10)
at ServerResponse.contentType (/node_modules/node-red/node_modules/express/lib/response.js:558:15)
at ServerResponse.sendStatus (/node_modules/node-red/node_modules/express/lib/response.js:346:8)
at /user/node_modules/node-red-contrib-meraki-cmx/cmx/merakiCMX.js:236:13
at Layer.handle [as handle_request] (/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
at next (/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
at /node_modules/node-red/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
at next (/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
at urlencodedParser (/shared_nodes/node-red-contrib-freeboard/node_modules/body-parser/lib/types/urlencoded.js:77:44)
at Layer.handle [as handle_request] (/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
at /node_modules/node-red/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
at next (/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
at expressInit (/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
at Layer.handle [as handle_request] (/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
at /node_modules/node-red/node_modules/express/lib/router/index.js:284:7
```

so,

1. It wasn't clear with the error report that the node was supplied with an invalid secret until I look at the console. Maybe you can send the error message to the debug tab instead? At this point, the node sent out a message in the debug tab like it was communicating with the remoteAddress properly. 

2. notice this error:
```
ReferenceError: msg is not defined
at /user/node_modules/node-red-contrib-meraki-cmx/cmx/merakiCMX.js:164:76
```

3. notice this error:
```
Error: Can't set headers after they are sent.
```

I was running meraki-cmx@1.1.1 and node-red@0.17.5

**Comment by dexterlabora** [comment]
Thanks for catching this. I found a few things that could be changed and will fix this for the next update.

**Comment by dexterlabora** [comment]
Fixed!

v1.1.2
https://www.npmjs.com/package/node-red-contrib-meraki-cmx
